name: nightly build

on:
  workflow_dispatch:
    inputs:     
      sha: 
        description: "The commit id you want to build"
        default: master
  push:
    branches: [ "general-feature" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    strategy:
      matrix:
        os:
          - [centos7,nebula-arm,arm64]
          - [centos7,nebula-fast,amd64]
    runs-on: 
      - self-hosted
      - ${{ matrix.os[1] }}
    container:
      image: golang:1.20
    steps:
      - uses: actions/checkout@v3
        with:
          repository: vesoft-inc/nebula-agent
          ref: ${{ inputs.sha }}
      - name: Build
        run: |
          sed -i '/license/s/.*//' go.mod
          rm -rf packages
          make build
      - uses: actions/upload-artifact@v2
        with:
          path: ./bin/
          name: agent-${{matrix.os[0]}}-${{ matrix.os[2] }}
